# import os
# import csv
# import json
# from datetime import datetime

# # ── Paths ─────────────────────────────────────────────────────────────────
# _ROOT     = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# DATA_DIR  = os.path.join(_ROOT, "data")
# _LOG_DIR  = os.path.join(_ROOT, "logs")
# _OUT_FILE = os.path.join(_LOG_DIR, "file_output.txt")

# os.makedirs(DATA_DIR, exist_ok=True)
# os.makedirs(_LOG_DIR, exist_ok=True)

# # ── Allowed extensions ────────────────────────────────────────────────────
# _ALLOWED_EXT = {".csv", ".txt"}

# # ── System prompt ─────────────────────────────────────────────────────────
# FILE_AGENT_SYSTEM_PROMPT = """
# You are the File Agent — a specialist in reading, writing, and managing files.

# YOUR JOB:
# 1. Read .txt and .csv files when asked.
# 2. Write or append content to .txt and .csv files.
# 3. Summarise file contents clearly in plain English.

# STRICT RULES:
# - Only handle .txt and .csv files.
# - When reading a CSV, describe its columns, row count, and a 3-row sample.
# - When writing, confirm the file path and number of bytes written.
# - Never fabricate file contents — only report what actually exists on disk.
# - If a file is not found, say so clearly and suggest checking the file name.
# - For CSV content generated by an LLM, ensure it has a proper header row.
# """


# def _resolve_path(file_name: str) -> str:
#     """Resolve file_name to an absolute path inside DATA_DIR."""
#     if os.path.isabs(file_name):
#         return file_name
#     return os.path.join(DATA_DIR, file_name)


# def _validate_ext(path: str) -> tuple[bool, str]:
#     ext = os.path.splitext(path)[1].lower()
#     if ext not in _ALLOWED_EXT:
#         return False, f"Unsupported file type '{ext}'. Only .csv and .txt are allowed."
#     return True, ""


# def _log_operation(action: str, file_name: str, detail: str) -> None:
#     """Append operation record to logs/file_output.txt."""
#     with open(_OUT_FILE, "a", encoding="utf-8") as f:
#         f.write(f"\n{'='*60}\n")
#         f.write(f"Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
#         f.write(f"Action    : {action.upper()}\n")
#         f.write(f"File      : {file_name}\n")
#         f.write(f"{'─'*60}\n")
#         f.write(detail + "\n")


# def file_manager(action: str, file_name: str, content: str = "") -> str:
#     """
#     Read, write, or append local .csv / .txt files.

#     Parameters
#     ----------
#     action    : "read" | "write" | "append"
#     file_name : filename (resolved relative to data/ dir if not absolute)
#     content   : text to write (used for "write" and "append")

#     Returns
#     -------
#     str — file content (read) or status message (write/append)
#     """
#     path = _resolve_path(file_name)

#     ok, err = _validate_ext(path)
#     if not ok:
#         return f"File Error: {err}"

#     try:
#         # ── READ ──────────────────────────────────────────────────────────
#         if action == "read":
#             if not os.path.exists(path):
#                 msg = f"Error: '{file_name}' not found in {DATA_DIR}."
#                 _log_operation("read", file_name, msg)
#                 return msg

#             with open(path, "r", encoding="utf-8") as f:
#                 data = f.read()

#             detail = f"Read {len(data)} bytes.\n\nCONTENT (first 500 chars):\n{data[:500]}"
#             _log_operation("read", file_name, detail)
#             return data

#         # ── WRITE ─────────────────────────────────────────────────────────
#         elif action == "write":
#             os.makedirs(os.path.dirname(path), exist_ok=True)
#             with open(path, "w", encoding="utf-8", newline="") as f:
#                 f.write(content)
#             size = os.path.getsize(path)
#             msg = f"Success: '{file_name}' written ({size} bytes) → {path}"
#             _log_operation("write", file_name, f"{msg}\n\nCONTENT WRITTEN:\n{content[:300]}")
#             return msg

#         # ── APPEND ────────────────────────────────────────────────────────
#         elif action == "append":
#             os.makedirs(os.path.dirname(path), exist_ok=True)
#             with open(path, "a", encoding="utf-8", newline="") as f:
#                 f.write(content)
#             size = os.path.getsize(path)
#             msg = f"Success: Appended to '{file_name}' (total {size} bytes) → {path}"
#             _log_operation("append", file_name, f"{msg}\n\nAPPENDED:\n{content[:300]}")
#             return msg

#         else:
#             return "File Error: Unknown action. Use 'read', 'write', or 'append'."

#     except Exception as exc:
#         msg = f"File Error: {type(exc).__name__}: {exc}"
#         _log_operation(action, file_name, msg)
#         return msg


# def save_analysis_report(query: str, report: str, file_name: str = "analysis_report.txt") -> str:
#     """
#     Save an analysis report to the data directory.
#     Called by orchestrator after every file/code pipeline run.
#     """
#     timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
#     full_content = (
#         f"{'='*60}\n"
#         f"Report Generated : {timestamp}\n"
#         f"User Query       : {query}\n"
#         f"{'─'*60}\n"
#         f"{report}\n"
#     )
#     return file_manager("append", file_name, full_content)


# # ── Tool descriptor ───────────────────────────────────────────────────────
# file_tool = {
#     "name":          "file_manager",
#     "description":   "Read, write, or append local .csv or .txt files.",
#     "func":          file_manager,
#     "system_prompt": FILE_AGENT_SYSTEM_PROMPT,
# }

"""
src/tools/file_agent.py
"""

import os

_ROOT    = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(_ROOT, "data")
os.makedirs(DATA_DIR, exist_ok=True)


def file_manager(action: str, file_name: str, content: str = "") -> str:
    """
    Read, write, or append .csv or .txt files in the data directory.

    Args:
        action:    'read', 'write', or 'append'.
        file_name: Filename only — stored in the data directory.
        content:   Text to write or append. Empty for 'read'.

    Returns:
        File content on read, confirmation with byte count on write/append,
        or an error string.
    """
    ext = os.path.splitext(file_name)[1].lower()
    if ext not in {".csv", ".txt"}:
        return f"Error: Unsupported file type '{ext}'. Only .csv and .txt are allowed."

    path = os.path.join(DATA_DIR, file_name)

    try:
        if action == "read":
            if not os.path.exists(path):
                return f"Error: '{file_name}' not found in {DATA_DIR}."
            with open(path, "r", encoding="utf-8") as f:
                return f.read()

        elif action == "write":
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(content)
            return f"Success: '{file_name}' written ({os.path.getsize(path)} bytes) → {path}"

        elif action == "append":
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "a", encoding="utf-8", newline="") as f:
                f.write(content)
            return f"Success: Appended to '{file_name}' (total {os.path.getsize(path)} bytes) → {path}"

        return "Error: Unknown action. Use 'read', 'write', or 'append'."

    except Exception as exc:
        return f"File Error: {type(exc).__name__}: {exc}"