events {}
http {
    server {
        listen 80;
        server_name app.local;
        # return 301 https://$host$request_uri;
        return 301 https://app.local$request_uri;
    }
    server{
        listen 443 ssl;
        server_name app.local;
        ssl_certificate /etc/nginx/ssl/app.local.pem;
        ssl_certificate_key /etc/nginx/ssl/app.local-key.pem;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /api/ {
            proxy_pass http://backend:3005;
            proxy_set_header Host $host;
        }
    }
}